services:
  rpc-content:
    build:
      context: .
      dockerfile: Dockerfile
    image: rpc-content:latest
    container_name: rpc-content
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./etc:/app/etc
    environment:
      - ETCD_ENDPOINTS=10.8.0.1:2379
    networks:
      - thinktalk-net

networks:
  thinktalk-net:
    driver: bridge
