// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: content.proto

package content

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Article_Publish_FullMethodName          = "/content.Article/Publish"
	Article_Articles_FullMethodName         = "/content.Article/Articles"
	Article_ArticleDelete_FullMethodName    = "/content.Article/ArticleDelete"
	Article_ArticleDetail_FullMethodName    = "/content.Article/ArticleDetail"
	Article_SearchArticles_FullMethodName   = "/content.Article/SearchArticles"
	Article_AdminPendingList_FullMethodName = "/content.Article/AdminPendingList"
	Article_AdminAudit_FullMethodName       = "/content.Article/AdminAudit"
)

// ArticleClient is the client API for Article service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --------------------------- 文章服务 -----------------------------
type ArticleClient interface {
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	Articles(ctx context.Context, in *ArticlesRequest, opts ...grpc.CallOption) (*ArticlesResponse, error)
	ArticleDelete(ctx context.Context, in *ArticleDeleteRequest, opts ...grpc.CallOption) (*ArticleDeleteResponse, error)
	ArticleDetail(ctx context.Context, in *ArticleDetailRequest, opts ...grpc.CallOption) (*ArticleDetailResponse, error)
	SearchArticles(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	AdminPendingList(ctx context.Context, in *AdminPendingListRequest, opts ...grpc.CallOption) (*AdminPendingListResponse, error)
	AdminAudit(ctx context.Context, in *AdminAuditRequest, opts ...grpc.CallOption) (*AdminAuditResponse, error)
}

type articleClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleClient(cc grpc.ClientConnInterface) ArticleClient {
	return &articleClient{cc}
}

func (c *articleClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, Article_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) Articles(ctx context.Context, in *ArticlesRequest, opts ...grpc.CallOption) (*ArticlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticlesResponse)
	err := c.cc.Invoke(ctx, Article_Articles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) ArticleDelete(ctx context.Context, in *ArticleDeleteRequest, opts ...grpc.CallOption) (*ArticleDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleDeleteResponse)
	err := c.cc.Invoke(ctx, Article_ArticleDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) ArticleDetail(ctx context.Context, in *ArticleDetailRequest, opts ...grpc.CallOption) (*ArticleDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleDetailResponse)
	err := c.cc.Invoke(ctx, Article_ArticleDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) SearchArticles(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, Article_SearchArticles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) AdminPendingList(ctx context.Context, in *AdminPendingListRequest, opts ...grpc.CallOption) (*AdminPendingListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminPendingListResponse)
	err := c.cc.Invoke(ctx, Article_AdminPendingList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) AdminAudit(ctx context.Context, in *AdminAuditRequest, opts ...grpc.CallOption) (*AdminAuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAuditResponse)
	err := c.cc.Invoke(ctx, Article_AdminAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServer is the server API for Article service.
// All implementations must embed UnimplementedArticleServer
// for forward compatibility.
//
// --------------------------- 文章服务 -----------------------------
type ArticleServer interface {
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	Articles(context.Context, *ArticlesRequest) (*ArticlesResponse, error)
	ArticleDelete(context.Context, *ArticleDeleteRequest) (*ArticleDeleteResponse, error)
	ArticleDetail(context.Context, *ArticleDetailRequest) (*ArticleDetailResponse, error)
	SearchArticles(context.Context, *SearchRequest) (*SearchResponse, error)
	AdminPendingList(context.Context, *AdminPendingListRequest) (*AdminPendingListResponse, error)
	AdminAudit(context.Context, *AdminAuditRequest) (*AdminAuditResponse, error)
	mustEmbedUnimplementedArticleServer()
}

// UnimplementedArticleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArticleServer struct{}

func (UnimplementedArticleServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedArticleServer) Articles(context.Context, *ArticlesRequest) (*ArticlesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Articles not implemented")
}
func (UnimplementedArticleServer) ArticleDelete(context.Context, *ArticleDeleteRequest) (*ArticleDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArticleDelete not implemented")
}
func (UnimplementedArticleServer) ArticleDetail(context.Context, *ArticleDetailRequest) (*ArticleDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArticleDetail not implemented")
}
func (UnimplementedArticleServer) SearchArticles(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchArticles not implemented")
}
func (UnimplementedArticleServer) AdminPendingList(context.Context, *AdminPendingListRequest) (*AdminPendingListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminPendingList not implemented")
}
func (UnimplementedArticleServer) AdminAudit(context.Context, *AdminAuditRequest) (*AdminAuditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminAudit not implemented")
}
func (UnimplementedArticleServer) mustEmbedUnimplementedArticleServer() {}
func (UnimplementedArticleServer) testEmbeddedByValue()                 {}

// UnsafeArticleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticleServer will
// result in compilation errors.
type UnsafeArticleServer interface {
	mustEmbedUnimplementedArticleServer()
}

func RegisterArticleServer(s grpc.ServiceRegistrar, srv ArticleServer) {
	// If the following call panics, it indicates UnimplementedArticleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Article_ServiceDesc, srv)
}

func _Article_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Article_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_Articles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).Articles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Article_Articles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).Articles(ctx, req.(*ArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_ArticleDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).ArticleDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Article_ArticleDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).ArticleDelete(ctx, req.(*ArticleDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_ArticleDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).ArticleDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Article_ArticleDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).ArticleDetail(ctx, req.(*ArticleDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_SearchArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).SearchArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Article_SearchArticles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).SearchArticles(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_AdminPendingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminPendingListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).AdminPendingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Article_AdminPendingList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).AdminPendingList(ctx, req.(*AdminPendingListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_AdminAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).AdminAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Article_AdminAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).AdminAudit(ctx, req.(*AdminAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Article_ServiceDesc is the grpc.ServiceDesc for Article service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Article_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "content.Article",
	HandlerType: (*ArticleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _Article_Publish_Handler,
		},
		{
			MethodName: "Articles",
			Handler:    _Article_Articles_Handler,
		},
		{
			MethodName: "ArticleDelete",
			Handler:    _Article_ArticleDelete_Handler,
		},
		{
			MethodName: "ArticleDetail",
			Handler:    _Article_ArticleDetail_Handler,
		},
		{
			MethodName: "SearchArticles",
			Handler:    _Article_SearchArticles_Handler,
		},
		{
			MethodName: "AdminPendingList",
			Handler:    _Article_AdminPendingList_Handler,
		},
		{
			MethodName: "AdminAudit",
			Handler:    _Article_AdminAudit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "content.proto",
}

const (
	QA_PublishQuestion_FullMethodName = "/content.QA/PublishQuestion"
	QA_AnswerQuestion_FullMethodName  = "/content.QA/AnswerQuestion"
	QA_AcceptAnswer_FullMethodName    = "/content.QA/AcceptAnswer"
	QA_Questions_FullMethodName       = "/content.QA/Questions"
	QA_QuestionDetail_FullMethodName  = "/content.QA/QuestionDetail"
	QA_QuestionDelete_FullMethodName  = "/content.QA/QuestionDelete"
	QA_AnswerList_FullMethodName      = "/content.QA/AnswerList"
	QA_AnswerDelete_FullMethodName    = "/content.QA/AnswerDelete"
	QA_SearchQuestions_FullMethodName = "/content.QA/SearchQuestions"
)

// QAClient is the client API for QA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --------------------------- 问答服务 -----------------------------
type QAClient interface {
	PublishQuestion(ctx context.Context, in *PublishQuestionRequest, opts ...grpc.CallOption) (*PublishQuestionResponse, error)
	AnswerQuestion(ctx context.Context, in *AnswerQuestionRequest, opts ...grpc.CallOption) (*AnswerQuestionResponse, error)
	AcceptAnswer(ctx context.Context, in *AcceptAnswerRequest, opts ...grpc.CallOption) (*AcceptAnswerResponse, error)
	Questions(ctx context.Context, in *QuestionsRequest, opts ...grpc.CallOption) (*QuestionsResponse, error)
	QuestionDetail(ctx context.Context, in *QuestionDetailRequest, opts ...grpc.CallOption) (*QuestionDetailResponse, error)
	QuestionDelete(ctx context.Context, in *QuestionDeleteRequest, opts ...grpc.CallOption) (*QuestionDeleteResponse, error)
	AnswerList(ctx context.Context, in *AnswerListRequest, opts ...grpc.CallOption) (*AnswerListResponse, error)
	AnswerDelete(ctx context.Context, in *AnswerDeleteRequest, opts ...grpc.CallOption) (*AnswerDeleteResponse, error)
	SearchQuestions(ctx context.Context, in *SearchQuestionsRequest, opts ...grpc.CallOption) (*SearchQuestionsResponse, error)
}

type qAClient struct {
	cc grpc.ClientConnInterface
}

func NewQAClient(cc grpc.ClientConnInterface) QAClient {
	return &qAClient{cc}
}

func (c *qAClient) PublishQuestion(ctx context.Context, in *PublishQuestionRequest, opts ...grpc.CallOption) (*PublishQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishQuestionResponse)
	err := c.cc.Invoke(ctx, QA_PublishQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qAClient) AnswerQuestion(ctx context.Context, in *AnswerQuestionRequest, opts ...grpc.CallOption) (*AnswerQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerQuestionResponse)
	err := c.cc.Invoke(ctx, QA_AnswerQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qAClient) AcceptAnswer(ctx context.Context, in *AcceptAnswerRequest, opts ...grpc.CallOption) (*AcceptAnswerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptAnswerResponse)
	err := c.cc.Invoke(ctx, QA_AcceptAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qAClient) Questions(ctx context.Context, in *QuestionsRequest, opts ...grpc.CallOption) (*QuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionsResponse)
	err := c.cc.Invoke(ctx, QA_Questions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qAClient) QuestionDetail(ctx context.Context, in *QuestionDetailRequest, opts ...grpc.CallOption) (*QuestionDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionDetailResponse)
	err := c.cc.Invoke(ctx, QA_QuestionDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qAClient) QuestionDelete(ctx context.Context, in *QuestionDeleteRequest, opts ...grpc.CallOption) (*QuestionDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionDeleteResponse)
	err := c.cc.Invoke(ctx, QA_QuestionDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qAClient) AnswerList(ctx context.Context, in *AnswerListRequest, opts ...grpc.CallOption) (*AnswerListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerListResponse)
	err := c.cc.Invoke(ctx, QA_AnswerList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qAClient) AnswerDelete(ctx context.Context, in *AnswerDeleteRequest, opts ...grpc.CallOption) (*AnswerDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerDeleteResponse)
	err := c.cc.Invoke(ctx, QA_AnswerDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qAClient) SearchQuestions(ctx context.Context, in *SearchQuestionsRequest, opts ...grpc.CallOption) (*SearchQuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchQuestionsResponse)
	err := c.cc.Invoke(ctx, QA_SearchQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QAServer is the server API for QA service.
// All implementations must embed UnimplementedQAServer
// for forward compatibility.
//
// --------------------------- 问答服务 -----------------------------
type QAServer interface {
	PublishQuestion(context.Context, *PublishQuestionRequest) (*PublishQuestionResponse, error)
	AnswerQuestion(context.Context, *AnswerQuestionRequest) (*AnswerQuestionResponse, error)
	AcceptAnswer(context.Context, *AcceptAnswerRequest) (*AcceptAnswerResponse, error)
	Questions(context.Context, *QuestionsRequest) (*QuestionsResponse, error)
	QuestionDetail(context.Context, *QuestionDetailRequest) (*QuestionDetailResponse, error)
	QuestionDelete(context.Context, *QuestionDeleteRequest) (*QuestionDeleteResponse, error)
	AnswerList(context.Context, *AnswerListRequest) (*AnswerListResponse, error)
	AnswerDelete(context.Context, *AnswerDeleteRequest) (*AnswerDeleteResponse, error)
	SearchQuestions(context.Context, *SearchQuestionsRequest) (*SearchQuestionsResponse, error)
	mustEmbedUnimplementedQAServer()
}

// UnimplementedQAServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQAServer struct{}

func (UnimplementedQAServer) PublishQuestion(context.Context, *PublishQuestionRequest) (*PublishQuestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishQuestion not implemented")
}
func (UnimplementedQAServer) AnswerQuestion(context.Context, *AnswerQuestionRequest) (*AnswerQuestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnswerQuestion not implemented")
}
func (UnimplementedQAServer) AcceptAnswer(context.Context, *AcceptAnswerRequest) (*AcceptAnswerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptAnswer not implemented")
}
func (UnimplementedQAServer) Questions(context.Context, *QuestionsRequest) (*QuestionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Questions not implemented")
}
func (UnimplementedQAServer) QuestionDetail(context.Context, *QuestionDetailRequest) (*QuestionDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QuestionDetail not implemented")
}
func (UnimplementedQAServer) QuestionDelete(context.Context, *QuestionDeleteRequest) (*QuestionDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QuestionDelete not implemented")
}
func (UnimplementedQAServer) AnswerList(context.Context, *AnswerListRequest) (*AnswerListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnswerList not implemented")
}
func (UnimplementedQAServer) AnswerDelete(context.Context, *AnswerDeleteRequest) (*AnswerDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnswerDelete not implemented")
}
func (UnimplementedQAServer) SearchQuestions(context.Context, *SearchQuestionsRequest) (*SearchQuestionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchQuestions not implemented")
}
func (UnimplementedQAServer) mustEmbedUnimplementedQAServer() {}
func (UnimplementedQAServer) testEmbeddedByValue()            {}

// UnsafeQAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QAServer will
// result in compilation errors.
type UnsafeQAServer interface {
	mustEmbedUnimplementedQAServer()
}

func RegisterQAServer(s grpc.ServiceRegistrar, srv QAServer) {
	// If the following call panics, it indicates UnimplementedQAServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QA_ServiceDesc, srv)
}

func _QA_PublishQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QAServer).PublishQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QA_PublishQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QAServer).PublishQuestion(ctx, req.(*PublishQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QA_AnswerQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QAServer).AnswerQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QA_AnswerQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QAServer).AnswerQuestion(ctx, req.(*AnswerQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QA_AcceptAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QAServer).AcceptAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QA_AcceptAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QAServer).AcceptAnswer(ctx, req.(*AcceptAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QA_Questions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QAServer).Questions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QA_Questions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QAServer).Questions(ctx, req.(*QuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QA_QuestionDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QAServer).QuestionDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QA_QuestionDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QAServer).QuestionDetail(ctx, req.(*QuestionDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QA_QuestionDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QAServer).QuestionDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QA_QuestionDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QAServer).QuestionDelete(ctx, req.(*QuestionDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QA_AnswerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QAServer).AnswerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QA_AnswerList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QAServer).AnswerList(ctx, req.(*AnswerListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QA_AnswerDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QAServer).AnswerDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QA_AnswerDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QAServer).AnswerDelete(ctx, req.(*AnswerDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QA_SearchQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchQuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QAServer).SearchQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QA_SearchQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QAServer).SearchQuestions(ctx, req.(*SearchQuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QA_ServiceDesc is the grpc.ServiceDesc for QA service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QA_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "content.QA",
	HandlerType: (*QAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishQuestion",
			Handler:    _QA_PublishQuestion_Handler,
		},
		{
			MethodName: "AnswerQuestion",
			Handler:    _QA_AnswerQuestion_Handler,
		},
		{
			MethodName: "AcceptAnswer",
			Handler:    _QA_AcceptAnswer_Handler,
		},
		{
			MethodName: "Questions",
			Handler:    _QA_Questions_Handler,
		},
		{
			MethodName: "QuestionDetail",
			Handler:    _QA_QuestionDetail_Handler,
		},
		{
			MethodName: "QuestionDelete",
			Handler:    _QA_QuestionDelete_Handler,
		},
		{
			MethodName: "AnswerList",
			Handler:    _QA_AnswerList_Handler,
		},
		{
			MethodName: "AnswerDelete",
			Handler:    _QA_AnswerDelete_Handler,
		},
		{
			MethodName: "SearchQuestions",
			Handler:    _QA_SearchQuestions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "content.proto",
}

const (
	Tag_CreateTag_FullMethodName      = "/content.Tag/CreateTag"
	Tag_UpdateTag_FullMethodName      = "/content.Tag/UpdateTag"
	Tag_DeleteTag_FullMethodName      = "/content.Tag/DeleteTag"
	Tag_TagDetail_FullMethodName      = "/content.Tag/TagDetail"
	Tag_TagList_FullMethodName        = "/content.Tag/TagList"
	Tag_HotTags_FullMethodName        = "/content.Tag/HotTags"
	Tag_TagResource_FullMethodName    = "/content.Tag/TagResource"
	Tag_UntagResource_FullMethodName  = "/content.Tag/UntagResource"
	Tag_ResourcesByTag_FullMethodName = "/content.Tag/ResourcesByTag"
	Tag_TagsByResource_FullMethodName = "/content.Tag/TagsByResource"
)

// TagClient is the client API for Tag service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --------------------------- 标签服务 -----------------------------
type TagClient interface {
	CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error)
	UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*UpdateTagResponse, error)
	DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error)
	TagDetail(ctx context.Context, in *TagDetailRequest, opts ...grpc.CallOption) (*TagDetailResponse, error)
	TagList(ctx context.Context, in *TagListRequest, opts ...grpc.CallOption) (*TagListResponse, error)
	HotTags(ctx context.Context, in *HotTagsRequest, opts ...grpc.CallOption) (*HotTagsResponse, error)
	TagResource(ctx context.Context, in *TagResourceRequest, opts ...grpc.CallOption) (*TagResourceResponse, error)
	UntagResource(ctx context.Context, in *UntagResourceRequest, opts ...grpc.CallOption) (*UntagResourceResponse, error)
	ResourcesByTag(ctx context.Context, in *ResourcesByTagRequest, opts ...grpc.CallOption) (*ResourcesByTagResponse, error)
	TagsByResource(ctx context.Context, in *TagsByResourceRequest, opts ...grpc.CallOption) (*TagsByResourceResponse, error)
}

type tagClient struct {
	cc grpc.ClientConnInterface
}

func NewTagClient(cc grpc.ClientConnInterface) TagClient {
	return &tagClient{cc}
}

func (c *tagClient) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTagResponse)
	err := c.cc.Invoke(ctx, Tag_CreateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*UpdateTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTagResponse)
	err := c.cc.Invoke(ctx, Tag_UpdateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTagResponse)
	err := c.cc.Invoke(ctx, Tag_DeleteTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) TagDetail(ctx context.Context, in *TagDetailRequest, opts ...grpc.CallOption) (*TagDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagDetailResponse)
	err := c.cc.Invoke(ctx, Tag_TagDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) TagList(ctx context.Context, in *TagListRequest, opts ...grpc.CallOption) (*TagListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagListResponse)
	err := c.cc.Invoke(ctx, Tag_TagList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) HotTags(ctx context.Context, in *HotTagsRequest, opts ...grpc.CallOption) (*HotTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HotTagsResponse)
	err := c.cc.Invoke(ctx, Tag_HotTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) TagResource(ctx context.Context, in *TagResourceRequest, opts ...grpc.CallOption) (*TagResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagResourceResponse)
	err := c.cc.Invoke(ctx, Tag_TagResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) UntagResource(ctx context.Context, in *UntagResourceRequest, opts ...grpc.CallOption) (*UntagResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UntagResourceResponse)
	err := c.cc.Invoke(ctx, Tag_UntagResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) ResourcesByTag(ctx context.Context, in *ResourcesByTagRequest, opts ...grpc.CallOption) (*ResourcesByTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourcesByTagResponse)
	err := c.cc.Invoke(ctx, Tag_ResourcesByTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) TagsByResource(ctx context.Context, in *TagsByResourceRequest, opts ...grpc.CallOption) (*TagsByResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagsByResourceResponse)
	err := c.cc.Invoke(ctx, Tag_TagsByResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TagServer is the server API for Tag service.
// All implementations must embed UnimplementedTagServer
// for forward compatibility.
//
// --------------------------- 标签服务 -----------------------------
type TagServer interface {
	CreateTag(context.Context, *CreateTagRequest) (*CreateTagResponse, error)
	UpdateTag(context.Context, *UpdateTagRequest) (*UpdateTagResponse, error)
	DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error)
	TagDetail(context.Context, *TagDetailRequest) (*TagDetailResponse, error)
	TagList(context.Context, *TagListRequest) (*TagListResponse, error)
	HotTags(context.Context, *HotTagsRequest) (*HotTagsResponse, error)
	TagResource(context.Context, *TagResourceRequest) (*TagResourceResponse, error)
	UntagResource(context.Context, *UntagResourceRequest) (*UntagResourceResponse, error)
	ResourcesByTag(context.Context, *ResourcesByTagRequest) (*ResourcesByTagResponse, error)
	TagsByResource(context.Context, *TagsByResourceRequest) (*TagsByResourceResponse, error)
	mustEmbedUnimplementedTagServer()
}

// UnimplementedTagServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTagServer struct{}

func (UnimplementedTagServer) CreateTag(context.Context, *CreateTagRequest) (*CreateTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTag not implemented")
}
func (UnimplementedTagServer) UpdateTag(context.Context, *UpdateTagRequest) (*UpdateTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTag not implemented")
}
func (UnimplementedTagServer) DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTag not implemented")
}
func (UnimplementedTagServer) TagDetail(context.Context, *TagDetailRequest) (*TagDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TagDetail not implemented")
}
func (UnimplementedTagServer) TagList(context.Context, *TagListRequest) (*TagListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TagList not implemented")
}
func (UnimplementedTagServer) HotTags(context.Context, *HotTagsRequest) (*HotTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HotTags not implemented")
}
func (UnimplementedTagServer) TagResource(context.Context, *TagResourceRequest) (*TagResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TagResource not implemented")
}
func (UnimplementedTagServer) UntagResource(context.Context, *UntagResourceRequest) (*UntagResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UntagResource not implemented")
}
func (UnimplementedTagServer) ResourcesByTag(context.Context, *ResourcesByTagRequest) (*ResourcesByTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResourcesByTag not implemented")
}
func (UnimplementedTagServer) TagsByResource(context.Context, *TagsByResourceRequest) (*TagsByResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TagsByResource not implemented")
}
func (UnimplementedTagServer) mustEmbedUnimplementedTagServer() {}
func (UnimplementedTagServer) testEmbeddedByValue()             {}

// UnsafeTagServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TagServer will
// result in compilation errors.
type UnsafeTagServer interface {
	mustEmbedUnimplementedTagServer()
}

func RegisterTagServer(s grpc.ServiceRegistrar, srv TagServer) {
	// If the following call panics, it indicates UnimplementedTagServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tag_ServiceDesc, srv)
}

func _Tag_CreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).CreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tag_CreateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).CreateTag(ctx, req.(*CreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_UpdateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).UpdateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tag_UpdateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).UpdateTag(ctx, req.(*UpdateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_DeleteTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).DeleteTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tag_DeleteTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).DeleteTag(ctx, req.(*DeleteTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_TagDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).TagDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tag_TagDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).TagDetail(ctx, req.(*TagDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_TagList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).TagList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tag_TagList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).TagList(ctx, req.(*TagListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_HotTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HotTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).HotTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tag_HotTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).HotTags(ctx, req.(*HotTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_TagResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).TagResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tag_TagResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).TagResource(ctx, req.(*TagResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_UntagResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UntagResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).UntagResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tag_UntagResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).UntagResource(ctx, req.(*UntagResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_ResourcesByTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourcesByTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).ResourcesByTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tag_ResourcesByTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).ResourcesByTag(ctx, req.(*ResourcesByTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_TagsByResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagsByResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).TagsByResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tag_TagsByResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).TagsByResource(ctx, req.(*TagsByResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tag_ServiceDesc is the grpc.ServiceDesc for Tag service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tag_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "content.Tag",
	HandlerType: (*TagServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTag",
			Handler:    _Tag_CreateTag_Handler,
		},
		{
			MethodName: "UpdateTag",
			Handler:    _Tag_UpdateTag_Handler,
		},
		{
			MethodName: "DeleteTag",
			Handler:    _Tag_DeleteTag_Handler,
		},
		{
			MethodName: "TagDetail",
			Handler:    _Tag_TagDetail_Handler,
		},
		{
			MethodName: "TagList",
			Handler:    _Tag_TagList_Handler,
		},
		{
			MethodName: "HotTags",
			Handler:    _Tag_HotTags_Handler,
		},
		{
			MethodName: "TagResource",
			Handler:    _Tag_TagResource_Handler,
		},
		{
			MethodName: "UntagResource",
			Handler:    _Tag_UntagResource_Handler,
		},
		{
			MethodName: "ResourcesByTag",
			Handler:    _Tag_ResourcesByTag_Handler,
		},
		{
			MethodName: "TagsByResource",
			Handler:    _Tag_TagsByResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "content.proto",
}
