// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: content.proto

package server

import (
	"context"

	"rpc-content/content"
	"rpc-content/internal/logic/article"
	"rpc-content/internal/svc"
)

type ArticleServer struct {
	svcCtx *svc.ServiceContext
	content.UnimplementedArticleServer
}

func NewArticleServer(svcCtx *svc.ServiceContext) *ArticleServer {
	return &ArticleServer{
		svcCtx: svcCtx,
	}
}

func (s *ArticleServer) Publish(ctx context.Context, in *content.PublishRequest) (*content.PublishResponse, error) {
	l := articlelogic.NewPublishLogic(ctx, s.svcCtx)
	return l.Publish(in)
}

func (s *ArticleServer) Articles(ctx context.Context, in *content.ArticlesRequest) (*content.ArticlesResponse, error) {
	l := articlelogic.NewArticlesLogic(ctx, s.svcCtx)
	return l.Articles(in)
}

func (s *ArticleServer) ArticleDelete(ctx context.Context, in *content.ArticleDeleteRequest) (*content.ArticleDeleteResponse, error) {
	l := articlelogic.NewArticleDeleteLogic(ctx, s.svcCtx)
	return l.ArticleDelete(in)
}

func (s *ArticleServer) ArticleDetail(ctx context.Context, in *content.ArticleDetailRequest) (*content.ArticleDetailResponse, error) {
	l := articlelogic.NewArticleDetailLogic(ctx, s.svcCtx)
	return l.ArticleDetail(in)
}

func (s *ArticleServer) SearchArticles(ctx context.Context, in *content.SearchRequest) (*content.SearchResponse, error) {
	l := articlelogic.NewSearchArticlesLogic(ctx, s.svcCtx)
	return l.SearchArticles(in)
}

func (s *ArticleServer) AdminPendingList(ctx context.Context, in *content.AdminPendingListRequest) (*content.AdminPendingListResponse, error) {
	l := articlelogic.NewAdminPendingListLogic(ctx, s.svcCtx)
	return l.AdminPendingList(in)
}

func (s *ArticleServer) AdminAudit(ctx context.Context, in *content.AdminAuditRequest) (*content.AdminAuditResponse, error) {
	l := articlelogic.NewAdminAuditLogic(ctx, s.svcCtx)
	return l.AdminAudit(in)
}
