// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: content.proto

package article

import (
	"context"

	"rpc-content/content"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminAuditRequest        = content.AdminAuditRequest
	AdminAuditResponse       = content.AdminAuditResponse
	AdminPendingListRequest  = content.AdminPendingListRequest
	AdminPendingListResponse = content.AdminPendingListResponse
	ArticleDeleteRequest     = content.ArticleDeleteRequest
	ArticleDeleteResponse    = content.ArticleDeleteResponse
	ArticleDetailRequest     = content.ArticleDetailRequest
	ArticleDetailResponse    = content.ArticleDetailResponse
	ArticlesRequest          = content.ArticlesRequest
	ArticlesResponse         = content.ArticlesResponse
	PublishRequest           = content.PublishRequest
	PublishResponse          = content.PublishResponse
	SearchRequest            = content.SearchRequest
	SearchResponse           = content.SearchResponse

	Article interface {
		Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
		Articles(ctx context.Context, in *ArticlesRequest, opts ...grpc.CallOption) (*ArticlesResponse, error)
		ArticleDelete(ctx context.Context, in *ArticleDeleteRequest, opts ...grpc.CallOption) (*ArticleDeleteResponse, error)
		ArticleDetail(ctx context.Context, in *ArticleDetailRequest, opts ...grpc.CallOption) (*ArticleDetailResponse, error)
		SearchArticles(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
		AdminPendingList(ctx context.Context, in *AdminPendingListRequest, opts ...grpc.CallOption) (*AdminPendingListResponse, error)
		AdminAudit(ctx context.Context, in *AdminAuditRequest, opts ...grpc.CallOption) (*AdminAuditResponse, error)
	}

	defaultArticle struct {
		cli zrpc.Client
	}
)

func NewArticle(cli zrpc.Client) Article {
	return &defaultArticle{
		cli: cli,
	}
}

func (m *defaultArticle) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	client := content.NewArticleClient(m.cli.Conn())
	return client.Publish(ctx, in, opts...)
}

func (m *defaultArticle) Articles(ctx context.Context, in *ArticlesRequest, opts ...grpc.CallOption) (*ArticlesResponse, error) {
	client := content.NewArticleClient(m.cli.Conn())
	return client.Articles(ctx, in, opts...)
}

func (m *defaultArticle) ArticleDelete(ctx context.Context, in *ArticleDeleteRequest, opts ...grpc.CallOption) (*ArticleDeleteResponse, error) {
	client := content.NewArticleClient(m.cli.Conn())
	return client.ArticleDelete(ctx, in, opts...)
}

func (m *defaultArticle) ArticleDetail(ctx context.Context, in *ArticleDetailRequest, opts ...grpc.CallOption) (*ArticleDetailResponse, error) {
	client := content.NewArticleClient(m.cli.Conn())
	return client.ArticleDetail(ctx, in, opts...)
}

func (m *defaultArticle) SearchArticles(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	client := content.NewArticleClient(m.cli.Conn())
	return client.SearchArticles(ctx, in, opts...)
}

func (m *defaultArticle) AdminPendingList(ctx context.Context, in *AdminPendingListRequest, opts ...grpc.CallOption) (*AdminPendingListResponse, error) {
	client := content.NewArticleClient(m.cli.Conn())
	return client.AdminPendingList(ctx, in, opts...)
}

func (m *defaultArticle) AdminAudit(ctx context.Context, in *AdminAuditRequest, opts ...grpc.CallOption) (*AdminAuditResponse, error) {
	client := content.NewArticleClient(m.cli.Conn())
	return client.AdminAudit(ctx, in, opts...)
}
