// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: content.proto

package server

import (
	"context"

	"rpc-content/content"
	"rpc-content/internal/logic/qa"
	"rpc-content/internal/svc"
)

type QAServer struct {
	svcCtx *svc.ServiceContext
	content.UnimplementedQAServer
}

func NewQAServer(svcCtx *svc.ServiceContext) *QAServer {
	return &QAServer{
		svcCtx: svcCtx,
	}
}

func (s *QAServer) PublishQuestion(ctx context.Context, in *content.PublishQuestionRequest) (*content.PublishQuestionResponse, error) {
	l := qalogic.NewPublishQuestionLogic(ctx, s.svcCtx)
	return l.PublishQuestion(in)
}

func (s *QAServer) AnswerQuestion(ctx context.Context, in *content.AnswerQuestionRequest) (*content.AnswerQuestionResponse, error) {
	l := qalogic.NewAnswerQuestionLogic(ctx, s.svcCtx)
	return l.AnswerQuestion(in)
}

func (s *QAServer) AcceptAnswer(ctx context.Context, in *content.AcceptAnswerRequest) (*content.AcceptAnswerResponse, error) {
	l := qalogic.NewAcceptAnswerLogic(ctx, s.svcCtx)
	return l.AcceptAnswer(in)
}

func (s *QAServer) Questions(ctx context.Context, in *content.QuestionsRequest) (*content.QuestionsResponse, error) {
	l := qalogic.NewQuestionsLogic(ctx, s.svcCtx)
	return l.Questions(in)
}

func (s *QAServer) QuestionDetail(ctx context.Context, in *content.QuestionDetailRequest) (*content.QuestionDetailResponse, error) {
	l := qalogic.NewQuestionDetailLogic(ctx, s.svcCtx)
	return l.QuestionDetail(in)
}

func (s *QAServer) QuestionDelete(ctx context.Context, in *content.QuestionDeleteRequest) (*content.QuestionDeleteResponse, error) {
	l := qalogic.NewQuestionDeleteLogic(ctx, s.svcCtx)
	return l.QuestionDelete(in)
}

func (s *QAServer) AnswerList(ctx context.Context, in *content.AnswerListRequest) (*content.AnswerListResponse, error) {
	l := qalogic.NewAnswerListLogic(ctx, s.svcCtx)
	return l.AnswerList(in)
}

func (s *QAServer) AnswerDelete(ctx context.Context, in *content.AnswerDeleteRequest) (*content.AnswerDeleteResponse, error) {
	l := qalogic.NewAnswerDeleteLogic(ctx, s.svcCtx)
	return l.AnswerDelete(in)
}

func (s *QAServer) SearchQuestions(ctx context.Context, in *content.SearchQuestionsRequest) (*content.SearchQuestionsResponse, error) {
	l := qalogic.NewSearchQuestionsLogic(ctx, s.svcCtx)
	return l.SearchQuestions(in)
}
