// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: content.proto

package qa

import (
	"context"

	"rpc-content/content"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AcceptAnswerRequest     = content.AcceptAnswerRequest
	AcceptAnswerResponse    = content.AcceptAnswerResponse
	AnswerDeleteRequest     = content.AnswerDeleteRequest
	AnswerDeleteResponse    = content.AnswerDeleteResponse
	AnswerListRequest       = content.AnswerListRequest
	AnswerListResponse      = content.AnswerListResponse
	AnswerQuestionRequest   = content.AnswerQuestionRequest
	AnswerQuestionResponse  = content.AnswerQuestionResponse
	PublishQuestionRequest  = content.PublishQuestionRequest
	PublishQuestionResponse = content.PublishQuestionResponse
	QuestionDeleteRequest   = content.QuestionDeleteRequest
	QuestionDeleteResponse  = content.QuestionDeleteResponse
	QuestionDetailRequest   = content.QuestionDetailRequest
	QuestionDetailResponse  = content.QuestionDetailResponse
	QuestionsRequest        = content.QuestionsRequest
	QuestionsResponse       = content.QuestionsResponse
	SearchQuestionsRequest  = content.SearchQuestionsRequest
	SearchQuestionsResponse = content.SearchQuestionsResponse

	QA interface {
		PublishQuestion(ctx context.Context, in *PublishQuestionRequest, opts ...grpc.CallOption) (*PublishQuestionResponse, error)
		AnswerQuestion(ctx context.Context, in *AnswerQuestionRequest, opts ...grpc.CallOption) (*AnswerQuestionResponse, error)
		AcceptAnswer(ctx context.Context, in *AcceptAnswerRequest, opts ...grpc.CallOption) (*AcceptAnswerResponse, error)
		Questions(ctx context.Context, in *QuestionsRequest, opts ...grpc.CallOption) (*QuestionsResponse, error)
		QuestionDetail(ctx context.Context, in *QuestionDetailRequest, opts ...grpc.CallOption) (*QuestionDetailResponse, error)
		QuestionDelete(ctx context.Context, in *QuestionDeleteRequest, opts ...grpc.CallOption) (*QuestionDeleteResponse, error)
		AnswerList(ctx context.Context, in *AnswerListRequest, opts ...grpc.CallOption) (*AnswerListResponse, error)
		AnswerDelete(ctx context.Context, in *AnswerDeleteRequest, opts ...grpc.CallOption) (*AnswerDeleteResponse, error)
		SearchQuestions(ctx context.Context, in *SearchQuestionsRequest, opts ...grpc.CallOption) (*SearchQuestionsResponse, error)
	}

	defaultQA struct {
		cli zrpc.Client
	}
)

func NewQA(cli zrpc.Client) QA {
	return &defaultQA{
		cli: cli,
	}
}

func (m *defaultQA) PublishQuestion(ctx context.Context, in *PublishQuestionRequest, opts ...grpc.CallOption) (*PublishQuestionResponse, error) {
	client := content.NewQAClient(m.cli.Conn())
	return client.PublishQuestion(ctx, in, opts...)
}

func (m *defaultQA) AnswerQuestion(ctx context.Context, in *AnswerQuestionRequest, opts ...grpc.CallOption) (*AnswerQuestionResponse, error) {
	client := content.NewQAClient(m.cli.Conn())
	return client.AnswerQuestion(ctx, in, opts...)
}

func (m *defaultQA) AcceptAnswer(ctx context.Context, in *AcceptAnswerRequest, opts ...grpc.CallOption) (*AcceptAnswerResponse, error) {
	client := content.NewQAClient(m.cli.Conn())
	return client.AcceptAnswer(ctx, in, opts...)
}

func (m *defaultQA) Questions(ctx context.Context, in *QuestionsRequest, opts ...grpc.CallOption) (*QuestionsResponse, error) {
	client := content.NewQAClient(m.cli.Conn())
	return client.Questions(ctx, in, opts...)
}

func (m *defaultQA) QuestionDetail(ctx context.Context, in *QuestionDetailRequest, opts ...grpc.CallOption) (*QuestionDetailResponse, error) {
	client := content.NewQAClient(m.cli.Conn())
	return client.QuestionDetail(ctx, in, opts...)
}

func (m *defaultQA) QuestionDelete(ctx context.Context, in *QuestionDeleteRequest, opts ...grpc.CallOption) (*QuestionDeleteResponse, error) {
	client := content.NewQAClient(m.cli.Conn())
	return client.QuestionDelete(ctx, in, opts...)
}

func (m *defaultQA) AnswerList(ctx context.Context, in *AnswerListRequest, opts ...grpc.CallOption) (*AnswerListResponse, error) {
	client := content.NewQAClient(m.cli.Conn())
	return client.AnswerList(ctx, in, opts...)
}

func (m *defaultQA) AnswerDelete(ctx context.Context, in *AnswerDeleteRequest, opts ...grpc.CallOption) (*AnswerDeleteResponse, error) {
	client := content.NewQAClient(m.cli.Conn())
	return client.AnswerDelete(ctx, in, opts...)
}

func (m *defaultQA) SearchQuestions(ctx context.Context, in *SearchQuestionsRequest, opts ...grpc.CallOption) (*SearchQuestionsResponse, error) {
	client := content.NewQAClient(m.cli.Conn())
	return client.SearchQuestions(ctx, in, opts...)
}
