// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: content.proto

package server

import (
	"context"

	"rpc-content/content"
	"rpc-content/internal/logic/tag"
	"rpc-content/internal/svc"
)

type TagServer struct {
	svcCtx *svc.ServiceContext
	content.UnimplementedTagServer
}

func NewTagServer(svcCtx *svc.ServiceContext) *TagServer {
	return &TagServer{
		svcCtx: svcCtx,
	}
}

func (s *TagServer) CreateTag(ctx context.Context, in *content.CreateTagRequest) (*content.CreateTagResponse, error) {
	l := taglogic.NewCreateTagLogic(ctx, s.svcCtx)
	return l.CreateTag(in)
}

func (s *TagServer) UpdateTag(ctx context.Context, in *content.UpdateTagRequest) (*content.UpdateTagResponse, error) {
	l := taglogic.NewUpdateTagLogic(ctx, s.svcCtx)
	return l.UpdateTag(in)
}

func (s *TagServer) DeleteTag(ctx context.Context, in *content.DeleteTagRequest) (*content.DeleteTagResponse, error) {
	l := taglogic.NewDeleteTagLogic(ctx, s.svcCtx)
	return l.DeleteTag(in)
}

func (s *TagServer) TagDetail(ctx context.Context, in *content.TagDetailRequest) (*content.TagDetailResponse, error) {
	l := taglogic.NewTagDetailLogic(ctx, s.svcCtx)
	return l.TagDetail(in)
}

func (s *TagServer) TagList(ctx context.Context, in *content.TagListRequest) (*content.TagListResponse, error) {
	l := taglogic.NewTagListLogic(ctx, s.svcCtx)
	return l.TagList(in)
}

func (s *TagServer) HotTags(ctx context.Context, in *content.HotTagsRequest) (*content.HotTagsResponse, error) {
	l := taglogic.NewHotTagsLogic(ctx, s.svcCtx)
	return l.HotTags(in)
}

func (s *TagServer) TagResource(ctx context.Context, in *content.TagResourceRequest) (*content.TagResourceResponse, error) {
	l := taglogic.NewTagResourceLogic(ctx, s.svcCtx)
	return l.TagResource(in)
}

func (s *TagServer) UntagResource(ctx context.Context, in *content.UntagResourceRequest) (*content.UntagResourceResponse, error) {
	l := taglogic.NewUntagResourceLogic(ctx, s.svcCtx)
	return l.UntagResource(in)
}

func (s *TagServer) ResourcesByTag(ctx context.Context, in *content.ResourcesByTagRequest) (*content.ResourcesByTagResponse, error) {
	l := taglogic.NewResourcesByTagLogic(ctx, s.svcCtx)
	return l.ResourcesByTag(in)
}

func (s *TagServer) TagsByResource(ctx context.Context, in *content.TagsByResourceRequest) (*content.TagsByResourceResponse, error) {
	l := taglogic.NewTagsByResourceLogic(ctx, s.svcCtx)
	return l.TagsByResource(in)
}
