// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: article.proto

package server

import (
	"context"

	"rpc-content/article/internal/logic"
	"rpc-content/article/internal/svc"
	"rpc-content/article/pb"
)

type ArticleServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedArticleServer
}

func NewArticleServer(svcCtx *svc.ServiceContext) *ArticleServer {
	return &ArticleServer{
		svcCtx: svcCtx,
	}
}

func (s *ArticleServer) Publish(ctx context.Context, in *pb.PublishRequest) (*pb.PublishResponse, error) {
	l := logic.NewPublishLogic(ctx, s.svcCtx)
	return l.Publish(in)
}

func (s *ArticleServer) Articles(ctx context.Context, in *pb.ArticlesRequest) (*pb.ArticlesResponse, error) {
	l := logic.NewArticlesLogic(ctx, s.svcCtx)
	return l.Articles(in)
}

func (s *ArticleServer) ArticleDelete(ctx context.Context, in *pb.ArticleDeleteRequest) (*pb.ArticleDeleteResponse, error) {
	l := logic.NewArticleDeleteLogic(ctx, s.svcCtx)
	return l.ArticleDelete(in)
}

func (s *ArticleServer) ArticleDetail(ctx context.Context, in *pb.ArticleDetailRequest) (*pb.ArticleDetailResponse, error) {
	l := logic.NewArticleDetailLogic(ctx, s.svcCtx)
	return l.ArticleDetail(in)
}

func (s *ArticleServer) SearchArticles(ctx context.Context, in *pb.SearchRequest) (*pb.SearchResponse, error) {
	l := logic.NewSearchArticlesLogic(ctx, s.svcCtx)
	return l.SearchArticles(in)
}

func (s *ArticleServer) AdminPendingList(ctx context.Context, in *pb.AdminPendingListRequest) (*pb.AdminPendingListResponse, error) {
	l := logic.NewAdminPendingListLogic(ctx, s.svcCtx)
	return l.AdminPendingList(in)
}

func (s *ArticleServer) AdminAudit(ctx context.Context, in *pb.AdminAuditRequest) (*pb.AdminAuditResponse, error) {
	l := logic.NewAdminAuditLogic(ctx, s.svcCtx)
	return l.AdminAudit(in)
}
