// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: content.proto

package tag

import (
	"context"

	"rpc-content/content"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateTagRequest       = content.CreateTagRequest
	CreateTagResponse      = content.CreateTagResponse
	DeleteTagRequest       = content.DeleteTagRequest
	DeleteTagResponse      = content.DeleteTagResponse
	HotTagsRequest         = content.HotTagsRequest
	HotTagsResponse        = content.HotTagsResponse
	ResourcesByTagRequest  = content.ResourcesByTagRequest
	ResourcesByTagResponse = content.ResourcesByTagResponse
	TagDetailRequest       = content.TagDetailRequest
	TagDetailResponse      = content.TagDetailResponse
	TagListRequest         = content.TagListRequest
	TagListResponse        = content.TagListResponse
	TagResourceRequest     = content.TagResourceRequest
	TagResourceResponse    = content.TagResourceResponse
	TagsByResourceRequest  = content.TagsByResourceRequest
	TagsByResourceResponse = content.TagsByResourceResponse
	UntagResourceRequest   = content.UntagResourceRequest
	UntagResourceResponse  = content.UntagResourceResponse
	UpdateTagRequest       = content.UpdateTagRequest
	UpdateTagResponse      = content.UpdateTagResponse

	Tag interface {
		CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error)
		UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*UpdateTagResponse, error)
		DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error)
		TagDetail(ctx context.Context, in *TagDetailRequest, opts ...grpc.CallOption) (*TagDetailResponse, error)
		TagList(ctx context.Context, in *TagListRequest, opts ...grpc.CallOption) (*TagListResponse, error)
		HotTags(ctx context.Context, in *HotTagsRequest, opts ...grpc.CallOption) (*HotTagsResponse, error)
		TagResource(ctx context.Context, in *TagResourceRequest, opts ...grpc.CallOption) (*TagResourceResponse, error)
		UntagResource(ctx context.Context, in *UntagResourceRequest, opts ...grpc.CallOption) (*UntagResourceResponse, error)
		ResourcesByTag(ctx context.Context, in *ResourcesByTagRequest, opts ...grpc.CallOption) (*ResourcesByTagResponse, error)
		TagsByResource(ctx context.Context, in *TagsByResourceRequest, opts ...grpc.CallOption) (*TagsByResourceResponse, error)
	}

	defaultTag struct {
		cli zrpc.Client
	}
)

func NewTag(cli zrpc.Client) Tag {
	return &defaultTag{
		cli: cli,
	}
}

func (m *defaultTag) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error) {
	client := content.NewTagClient(m.cli.Conn())
	return client.CreateTag(ctx, in, opts...)
}

func (m *defaultTag) UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*UpdateTagResponse, error) {
	client := content.NewTagClient(m.cli.Conn())
	return client.UpdateTag(ctx, in, opts...)
}

func (m *defaultTag) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error) {
	client := content.NewTagClient(m.cli.Conn())
	return client.DeleteTag(ctx, in, opts...)
}

func (m *defaultTag) TagDetail(ctx context.Context, in *TagDetailRequest, opts ...grpc.CallOption) (*TagDetailResponse, error) {
	client := content.NewTagClient(m.cli.Conn())
	return client.TagDetail(ctx, in, opts...)
}

func (m *defaultTag) TagList(ctx context.Context, in *TagListRequest, opts ...grpc.CallOption) (*TagListResponse, error) {
	client := content.NewTagClient(m.cli.Conn())
	return client.TagList(ctx, in, opts...)
}

func (m *defaultTag) HotTags(ctx context.Context, in *HotTagsRequest, opts ...grpc.CallOption) (*HotTagsResponse, error) {
	client := content.NewTagClient(m.cli.Conn())
	return client.HotTags(ctx, in, opts...)
}

func (m *defaultTag) TagResource(ctx context.Context, in *TagResourceRequest, opts ...grpc.CallOption) (*TagResourceResponse, error) {
	client := content.NewTagClient(m.cli.Conn())
	return client.TagResource(ctx, in, opts...)
}

func (m *defaultTag) UntagResource(ctx context.Context, in *UntagResourceRequest, opts ...grpc.CallOption) (*UntagResourceResponse, error) {
	client := content.NewTagClient(m.cli.Conn())
	return client.UntagResource(ctx, in, opts...)
}

func (m *defaultTag) ResourcesByTag(ctx context.Context, in *ResourcesByTagRequest, opts ...grpc.CallOption) (*ResourcesByTagResponse, error) {
	client := content.NewTagClient(m.cli.Conn())
	return client.ResourcesByTag(ctx, in, opts...)
}

func (m *defaultTag) TagsByResource(ctx context.Context, in *TagsByResourceRequest, opts ...grpc.CallOption) (*TagsByResourceResponse, error) {
	client := content.NewTagClient(m.cli.Conn())
	return client.TagsByResource(ctx, in, opts...)
}
